### ISSUE TITLE
Incomplete output.dot and difficulties to treat prof inputs with "spontaneous" routines with gprof2dot

### ISSUE THREAD

**Issue by Jajaazz** [jrfonseca/gprof2dot#100]
Hello there,

I am using gprof2dot to document my Fortran 90 program. It is quite complex and a visual call graph would be a blessing for a better understanding of what my code is doing. Even though gprof2dot has worked for some of my programs, I have some difficulties with the programs that show many spontaneous routines.
So what I used to do for some programs was to change the gprof output by removing the lines of the call graph part where there was a spontaneous function. In general, the spontaneous functions were located at the beginning of the call graph, because they are so time consuming; so that was easy. That worked until I started documenting a model that gives a gprof output with spontaneous functions that were not only at the beginning of the output report, but also in the middle of the call graph. There is no error when I run gprof2dot, but the output.dot isn't complete, compared to my input; no matter how many unwanted lines I crop in the gprof output.

Has anyone ever had this kind of problem ? Or is there anyone that could help me out on this ?

**Comment by jrfonseca** [comment]
[gprof's manual](https://ftp.gnu.org/old-gnu/Manuals/gprof-2.9.1/html_chapter/gprof_5.html#:~:text=if%20the%20identity%20of%20the%20callers%20of%20a%20function%20cannot%20be%20determined%2C%20a%20dummy%20caller-line%20is%20printed%20which%20has%20%60%3Cspontaneous%3E'%20as%20the%20%22caller's%20name%22%20and%20all%20other%20fields%20blank.%20this%20can%20happen%20for%20signal%20handlers.) states:

_"If the identity of the callers of a function cannot be determined, a dummy caller-line is printed which has `<spontaneous>` as the "caller's name" and all other fields blank. This can happen for signal handlers."_

I'd start by ensure you're setting the right options to Fortran compiler, like [these](https://github.com/jrfonseca/gprof2dot/?tab=readme-ov-file#which-options-should-i-pass-to-gcc-when-compiling-for-profiling) for GFortran case.

Are the functions called your functions, or system libraries' functions?

It would help me understand the problem better if you could provide me the gprof output before and after your edits.

**Comment by jrfonseca** [comment]
Thanks.

Is this data really correct?  More me gprof2dot.py fails due to `function_251` being referred in the gprof report but not have its own entry:

```
Traceback (most recent call last):
  File "/home/jfonseca/scripts/gprof2dot.py", line 3879, in <module>
    main()
  File "/home/jfonseca/scripts/gprof2dot.py", line 3826, in main
    profile = parser.parse()
              ^^^^^^^^^^^^^^
  File "/home/jfonseca/scripts/gprof2dot.py", line 1390, in parse
    profile.ratio(TIME_RATIO, TIME)
  File "/home/jfonseca/scripts/gprof2dot.py", line 733, in ratio
    assert inevent in function
           ^^^^^^^^^^^^^^^^^^^
AssertionError
```

Also please rebuild adding the  `-fno-omit-frame-pointer` compiler option and retry.

**Comment by Jajaazz** [comment]
Oh sorry, I made a mistake when I changed the name of the functions. Here is the version that has worked on my side.

So again, I have attached the same files, but with the new option for the compiler : 

    report_1.txt : the gprof output that was not altered
    output1.dot : the output of gprof2dot with report_1
    report_2.txt : the gprof output that I have altered by removing the lines for the spontaneous functions
    output2.dot : the output of gprof2dot with report 2.

[output1_new_options.txt](https://github.com/user-attachments/files/17772384/output1_new_options.txt)
[output2_new_options.txt](https://github.com/user-attachments/files/17772385/output2_new_options.txt)
[report1_new_compiler.txt](https://github.com/user-attachments/files/17772386/report1_new_compiler.txt)
[report2_new_compiler.txt](https://github.com/user-attachments/files/17772387/report2_new_compiler.txt)


I have tried the new option for the compiler, it has worked for one of my models, I was able to create a correct graph with it, but it only changed slightly the report. Thank your for your investment in my project !

**Comment by jrfonseca** [comment]
Thanks.

AFAICT, the fundamental problem is that:
1. these apparently non-interesting spontaneous functions lack call stack information,
2. too little CPU time is spent on the interesting functions.

For your particular case, maybe pruning out all these spontaneous functions solves the issue, but it's not generally the right thing to do.  gprof2dot didn't prune them because a significant amount of CPU was spent on them, relative to the rest.

In short, your gprof report has poor signal-to-noise ratio.

There are two ways to address this:
1. fix stack backtracing for the spontaneous functions, for example:
  - ensure the calling functions was also built with -pg
  - use a different profiler (e.g., [perf](https://github.com/jrfonseca/gprof2dot?tab=readme-ov-file#linux-perf) )
2. make sure the code you're interested actually gets more CPU time spent on (e.g, pass more data, or the code of interest in a loop) then gprof2dot.py will automatically prune the rest 

I hope this helps.  From gprof2dot's perspective, there's nothing actionable.

**Comment by Jajaazz** [comment]
Alright thank you for your time and advice. Indeed I knew there was something strange about the CPU time when I first saw the profiling reports. I'll try all this to try to fix all of this. At least now I know I did not miss anything on gprof2dot. 

Thanks again !
