### ISSUE TITLE
PyPI links to old home page

### ISSUE THREAD

**Issue by mgedmin** [jrfonseca/gprof2dot#13]
https://pypi.python.org/pypi/gprof2dot currently links to https://code.google.com/p/jrfonseca/wiki/Gprof2Dot, instead of GitHub.  I see you've fixed that in your setup.py already, so the next release will update the PyPI link too, but you don't have to wait for that.  You can also log in to PyPI over the web and update the home page link in a web form.

**Comment by jrfonseca** [comment]
Fixed. Thanks
