### ISSUE TITLE
Module name may not be sufficient for Python profiles

### ISSUE THREAD

**Issue by mgedmin** [jrfonseca/gprof2dot#14]
Python profiles are sometimes hard to read because all you see is:
- module name
- line number
- function/method name

but you don't see
- package name
- class name

There may be a dozen different modules with the same name in different packages, and don't let me get started about methods called `__init__`.

Now it's hard to do anything about class names if the profiling data doesn't contain that information (at least on Python 2.7; Python 3 introduced `__qualname__` that gives me hope for the eventual bright future, although I haven't actually checked if the profiler records those).

Package names are also difficult, since all we have is filenames.  (If the files still exist you could walk up the tree looking for `__init__.py` files: when these stop, you found the root package.  Except Python 3.3 breaks that heuristic with its implicit namespace packages and anyway, you cannot always rely on having the source code available -- what if the profile was made on a different machine?).

Still, not all hope is lost: the full filename is available, and humans can figure out the package name from that (or look up the class name from filename + line number).  Filenames are long, though, and would not fit in the graph nicely -- but wouldn't it be awesome if they were available via tooltips?

Certain graphviz formats (such as SVG) support tooltips.  I have a patch prepared.

**Comment by jrfonseca** [comment]
For the record, different workarounds have been presented to the same root issue:

https://code.google.com/archive/p/jrfonseca/issues/75
https://code.google.com/archive/p/jrfonseca/issues/87

The problem with the previous workarounds was that they relied on the Python system path to guess the qualified package name, which would create a bunch of problems.

Your approach of a tooltip doesn't have that drawback.
