### ISSUE TITLE
Too slow on a big cycle

### ISSUE THREAD

**Issue by chelzy** [jrfonseca/gprof2dot#17]
I have profile data in the _sleepy_ format. The data contains about 14000 functions with a huge cycle (~7500). Processing data takes about 6 hours.

I fixed the problem. The processing time was reduced to 2 minutes. I want to share the fix. The patch ([gprof2dot.py.diff.txt](https://github.com/jrfonseca/gprof2dot/files/91746/gprof2dot.py.diff.txt)) consists of the following changes
* improved implementation of Tarjan's algorithm to search for cycles
* ranking of cycle functions uses the Dijkstra's algorithm to search for shortest paths

**Comment by chelzy** [comment]
I have some other useful (I hope) changes. I don't want create a separate issue so I attached the patch here. The patch ([gprof2dot.py.diff-2.txt](https://github.com/jrfonseca/gprof2dot/files/91793/gprof2dot.py.diff-2.txt)) contains all the changes from the patch in the description and

* if `--root=ROOT` option is specified, do not eliminate the _ROOT_ node and all its **direct** descendants regardless of threshold values
* if `--leaf=LEAF` option is specified, do not eliminate the _LEAF_ node and all its **direct** ancestors regardless of threshold values

If you find these changes useful it is better to add a new option for such behavior.

**Comment by jrfonseca** [comment]
Two requests:

- instead of temporarily attaching `_tarjan_xxx` attributes to functions, could you please update your patch to use dictionaries (indexed by function.id, which is guaranteed to be unique)?

- could you make your code work on Python 3 too: it runs fine on python 2, but if I run the `tests/test.py` script with python3, it causes many crashes

**Comment by chelzy** [comment]
Changes:
* Tarjan's algorithm uses dictionary instead of the `_tarjan_xxx` attributes
* The code works on Python 3

[gprof2dot.py.diff.txt](https://github.com/jrfonseca/gprof2dot/files/103049/gprof2dot.py.diff.txt)

**Comment by jrfonseca** [comment]
Thanks.  I've pushed your optimizations.

Regarding the `--root`/`--leaf` changes, I'm not sure if changing the semantics of the options, or adding new options is justified.  The problem is that I never use these myself -- I always navigate the full graph with `xdot.py`.
