### ISSUE TITLE
Problems with Intel VTune Amplifier XE 2015

### ISSUE THREAD

**Issue by NunoOliv** [jrfonseca/gprof2dot#20]
I'm having problems with files generated from the latest version of VTune running on windows 10. I get " unrecognized call graph entry" warning for every line of the file. From what i could tell the problem is the lack of carriage return in files generated in VTune. I tried running the files in the test folder and the graphs were created successfully but when i used a program to remove the carriage returns from the files the graphs came out empty.

**Comment by jrfonseca** [comment]
I'm afraid I haven't been able to repro this.

With or without carriage returns, gprof2dot.py works ok on Windows 10 with VTune samples.  I'm using Python 2.

More importantly, the script opens files in text mode, so it should make no difference really...
