### ISSUE TITLE
Great Project. Needs a License.

### ISSUE THREAD

**Issue by bheni** [jrfonseca/gprof2dot#24]
I'd really like to use your code, but there is no license.  Please consider adding a license to your code. This site is a good source for understanding licences: [http://choosealicense.com](http://choosealicense.com).  An Apache or MIT license would be very useful.

Thanks.

**Comment by jrfonseca** [comment]
The code does have a license (LGPLv3).  See https://github.com/jrfonseca/gprof2dot/blob/master/gprof2dot.py .  But I added a full copy of the license text anyway,
