### ISSUE TITLE
Is the latest version compatible with Python3?

### ISSUE THREAD

**Issue by indera** [jrfonseca/gprof2dot#25]
Using the version from brew I am getting the following:
brew info gprof2dot
gprof2dot: stable 2015.02.03 (bottled), HEAD
Convert the output from many profilers into a Graphviz dot graph.
https://github.com/jrfonseca/gprof2dot
/usr/local/Cellar/gprof2dot/2015.02.03 (10 files, 202.0K) *
  Poured from bottle on 2016-10-12 at 13:32:44
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gprof2dot.rb
==> Dependencies
Recommended: graphviz ✔
==> Options
--without-graphviz
	Build without graphviz support
--HEAD
	Install HEAD version

Traceback (most recent call last):
  File "/usr/local/Cellar/gprof2dot/2015.02.03/libexec/bin/gprof2dot", line 9, in <module>
    load_entry_point('gprof2dot==2015.02.03', 'console_scripts', 'gprof2dot')()
  File "/usr/local/Cellar/gprof2dot/2015.02.03/libexec/lib/python2.7/site-packages/gprof2dot.py", line 3139, in main
    parser = Format(*args)
  File "/usr/local/Cellar/gprof2dot/2015.02.03/libexec/lib/python2.7/site-packages/gprof2dot.py", line 2565, in __init__
    self.stats = hotshot.stats.load(filename[0])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hotshot/stats.py", line 12, in load
    return StatsLoader(filename).load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hotshot/stats.py", line 29, in load
    for event in log:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hotshot/log.py", line 98, in next
    what, tdelta, fileno, lineno = self._nextitem()
ValueError: unknown record type in log file

**Comment by jrfonseca** [comment]
`2015.02.03` is really old.  You can get a newer version from through other means ( https://github.com/jrfonseca/gprof2dot#download ) or report the issue to brew, as I'm not responsible for it.

**Comment by zbeekman** [comment]
I was the one to add this formula to homebrew, and I apologize for not updating it more frequently... 

@indera and @jrfonseca: any idea if upgrading to a newer version will fix this issue?

**Comment by jrfonseca** [comment]
I'm running all tests on Python 3.4 and 3.5 in Travis -- https://github.com/jrfonseca/gprof2dot/blob/master/.travis.yml  --, so it should work.

The problem here is that one needs to execute gprof2dot.py with Python 3 when reading Python 3 stats, and Python 2 when reading Python 2 stats.

There's no way around it.  No matter what Python version is used by brew, this will always be an issue. 

Anyway, gprof2dot.py is a single script file.  So @indera , I recommend you just download the script, run it with Python3 interpret, and get on with the stuff you want to do.

**Comment by indera** [comment]
@jrfonseca Thank you!

**Comment by indera** [comment]
@zbeekman The latest tag to use for brew: https://pypi.python.org/pypi/gprof2dot/2016.10.12

**Comment by zbeekman** [comment]
I'll try to get to this tomorrow. If there are no dependency updates, it should be fairly trivial, and you're welcome to submit a PR to homebrew before I do if you're so inclined.

**Comment by zbeekman** [comment]
@jrfonseca and @indera if I install the latest version from pypi I get this error: 

```
$ gprof2dot --help
Traceback (most recent call last):
  File "/usr/local/bin/gprof2dot", line 7, in <module>
    from gprof2dot import main
  File "/usr/local/lib/python3.5/site-packages/gprof2dot.py", line 3281, in <module>
    raise Exception('using gprof2dot.py as a module is unsupported')
Exception: using gprof2dot.py as a module is unsupported
```

The same problem seems to pop up with homebrew installs too.

**Comment by jrfonseca** [comment]
My bad.  It looks that my hack to prevent people from accessing gprof2dot internals broke the distutils...

**Comment by jrfonseca** [comment]
Should be fixed now with https://pypi.python.org/pypi/gprof2dot/2016.10.13

**Comment by zbeekman** [comment]
seems to work from pypi now.... my local homebrew install on this computer is borked, but I [submitted a PR](https://github.com/Homebrew/homebrew-core/pull/5876) and CI tests will be sufficient to ensure that it's working since it's such a simple package.
