### ISSUE TITLE
Please release a tagged version to pypi

### ISSUE THREAD

**Issue by indera** [jrfonseca/gprof2dot#26]
It looks like the last version released was 
https://pypi.python.org/pypi/gprof2dot/2015.12.1

When you consider it is time maybe you can release a tagged version such as 0.0.1 so we can keep track of the code evolution.

Thank you!

**Comment by jrfonseca** [comment]
I've made a new PyPI release.

I had MAJOR.MINOR version scheme before, but there will never be a major bump again, as the script only get minors improvements.   Hence moving to YYYY.MM.DD , has some more meaning that an ever incrementing minor version.

**Comment by indera** [comment]
@jrfonseca Thank you for https://pypi.python.org/pypi/gprof2dot/2016.10.12
