### ISSUE TITLE
(Code rot) perf script format has changed

### ISSUE THREAD

**Issue by jrhacker** [jrfonseca/gprof2dot#28]
The output from perf script has changed.  Where it used to say

    7f023a570d85 __libc_start_main (/lib64/libc-2.17.so)

Now (kernel version 4.8.12) it says

    207d0 __libc_start_main+0xffff0082383ac0f0 (/lib64/libc-2.23.so)

gprof2dot.py needs an adjustment to avoid parsing the suffixed address as part of the function name.

[gprof2dot-patch.txt](https://github.com/jrfonseca/gprof2dot/files/637469/gprof2dot-patch.txt)

**Comment by jrfonseca** [comment]
I see.  Thanks.

But the regex fix needs to be a bit more generic in order to cope with C++ symbols and `c++filt` (ie, when doing `perf script | c++filt | gprof2dot.py -f perf` as recommended in the README.  Because demangled C++ symbols can have space and `+`.

Either we use non-greedy regex for the symbol (to avoid consume +0x....), or we leave this regex as is, and strip trailing offsets with a seperate regex..

**Comment by jrfonseca** [comment]
Another alternative is to replace the instructions to not invoke `c++filt`, and instead invoke `c++filt` internally.

**Comment by jrhacker** [comment]
c++filt may be redundant.  From perf script man page:

    --demangle
      Demangle symbol names to human readable form. It's enabled by
      default, disable with --no-demangle.

With the attached example, perf script by default demangles operator+ and produces output like this:

    62a operator++0xffffffffff800004 (/home/mumble/tmp/gprofc++/example)

perf script --no-demangle followed by c++filt instead produces output like
this:

    627 operator+(Blivet, Blivet)+0xffffffffff800001 (/home/mumble/tmp/gprofc++/example)

The attached revised patch does a non-clever, after-the-fact amputation of the address that handles both cases correctly.

[gprof2dot-patchv2.txt](https://github.com/jrfonseca/gprof2dot/files/639851/gprof2dot-patchv2.txt)
[examplecc.txt](https://github.com/jrfonseca/gprof2dot/files/639855/examplecc.txt)

**Comment by jrhacker** [comment]
Oops.  Don't crash if function_name is None.

[gprof2dot-patchv3.txt](https://github.com/jrfonseca/gprof2dot/files/640026/gprof2dot-patchv3.txt)

**Comment by jrhacker** [comment]
Oops.  Don't crash if function_name is None.

[gprof2dot-patchv3.txt](https://github.com/jrfonseca/gprof2dot/files/640044/gprof2dot-patchv3.txt)

**Comment by jrfonseca** [comment]
Finally pushed the fix. Thanks.
