### ISSUE TITLE
Assertion failure thrown due to computational inaccuracies

### ISSUE THREAD

**Issue by radekg1000** [jrfonseca/gprof2dot#29]
When running gprof2dot.py on my prof file the following assertion is thrown:

>   ...
File "./gprof2dot.py", line 558, in _integrate_cycle
    assert partial == max(partials.values())

After having modified the line 558 to:
`assert partial == max(partials.values()) , "partial=%r, max(partials.values)=%r, partial=max(partials.values)=%r" % (str(partial), str(max(partials.values())), str(partial - max(partials.values())))`

more details are shown:

>   File "./gprof2dot.py", line 558, in _integrate_cycle
    assert partial == max(partials.values()) , "partial=%r, max(partials.values)=%r, partial=max(partials.values)=%r" % (str(partial), str(max(partials.values())), str(partial - max(partials.values())))
AssertionError: partial='2.50626729881e-07', max(partials.values)='2.50626729881e-07', partial-max(partials.values)='-5.29395592034e-23'

The result is shown on 95% of runs of gprof2dot.py script on the varying perf output file.

Please could we modify the script to be more resilient against roundoff errors? e.g.:

`if partial != 0.0:`
`<tab>assert abs(partial - max(partials.values())) / abs(partial) <= 1e-7`

**Comment by jrfonseca** [comment]
Would it be possible to provide a sample input?

**Comment by radekg1000** [comment]
Please find attached file which is problematic to gprof2dot.py due to size and roundoff errors.
[roadsideapp.prof.zip](https://github.com/jrfonseca/gprof2dot/files/722376/roadsideapp.prof.zip)

**Comment by radekg1000** [comment]
This is a patch that I use to process this (and other) files.

[partial-assertion-roundoff-error-fix.patch.zip](https://github.com/jrfonseca/gprof2dot/files/722380/partial-assertion-roundoff-error-fix.patch.zip)

**Comment by radekg1000** [comment]
Hello José,

I have submitted the sample input on github some time ago. Additionally 
I have provided a patch to cope with the problem.
Are there any chances to have it integrated into the new version so that 
I do not have to modify my local one :-)?

Kind Regards
Radek

**Comment by jrfonseca** [comment]
Hi Radek,

Thanks for the repro and patch, and your patience.  

I usually have very little free time, but over the last 4 weeks I've been sick and my 2nd kid was born, so I hadn't no time for even the simplest of things.

I've tweaked you change a bit, so that the assertion expression works all the way to zero, and pushed it.

At some point I shall make a new pypi release with the recent fixes, but honestly I can't give an ETA.

**Comment by radekg1000** [comment]
Hi José,

Thank you for your reply and accepting my change.

Congratulations for the new baby! I have three and I know how difficult 
it is with time and generally :-).

Regards

Radek
