### ISSUE TITLE
See absolute time instead of percentage on nodes

### ISSUE THREAD

**Issue by chadaustin** [jrfonseca/gprof2dot#3]
Sometimes it's easier to reason about the performance of some code when you can see absolute times per node rather than percentage of total runtime.  For example, you might know a query ought to take 10 ms and if a function that only issues a query is taking 50 ms, it might be the clue you needed.  It's easier to detect stuff like this when absolute times are displayed rather than "this function was 0.5% of total runtime".

It would be nice to see total time in a function as well as average time per call.

**Comment by pthedinger** [comment]
I've done this in my own view by simply modifying line 2935 to have:

    show_function_events = [TOTAL_TIME_RATIO, TIME_RATIO, TIME]

And I've changed the format of TIME to be the time in ms (which it is for my case) by changing line 154:

TIME = Event("Time", 0.0, add, lambda x: str(x) + 'ms')

I know this is not the prettiest way to do it. It would be nice to have the timescale picked up automatically, and have this turned on by a flag. However, if you want to hack it for your own case then this might point you in the right direction.

**Comment by jrfonseca** [comment]
Does https://github.com/jrfonseca/gprof2dot/pull/23 meet your needs?

**Comment by jrfonseca** [comment]
@robinst Sounds good.  Rather than multiple options, I'd prefer a single `--label=MEASURE` option where `MEASURE` is `self-time`, `total-time`, `self-time-percentage`, ``total-time-percentage` (default.)

**Comment by robinst** [comment]
Sounds good! For multiple labels, would you be able to specify the option multiple times, e.g. `--label=total-time --label=total-time-percentage --label=self-time-percentage`?

**Comment by jrfonseca** [comment]
Sure, if the logic doesn't get too complex, no objections.
