### ISSUE TITLE
problem with callgrind

### ISSUE THREAD

**Issue by gustafn** [jrfonseca/gprof2dot#35]
is the are problem in gprof2dot with the callgrind parser?  gprof2dot can't process a callgrind file (see start of file below). When gprof2dot is called with

`python2.7   /usr/local/src/gprof2dot/gprof2dot.py --format=callgrind callgrind.out.8976-01 
`
gprof2dot complains:
```
warning: line 2: unexpected line
version: 1
digraph {
	graph [fontname=Arial, nodesep=0.125, ranksep=0.25];
	node [fontcolor=white, fontname=Arial, height=0, shape=box, style=filled, width=0];
	edge [fontname=Arial];
}

```
This looks like a principal problem with the callgrind format parser. Using instead python3.5 changes nothing. This happens on debian buster/sid.  Looks like something stupid, maybe on my side... I tried as well the version tags/2016.10.13.

-gn

Begin of callgrind.out.8976-01:
```
# callgrind format
version: 1
creator: callgrind-3.13.0
pid: 8976

```

**Comment by foxcpp** [comment]
I have exactly same problem, 
Arch Linux, gprof2dot 2016.10.13 installed using pip, Python 3.6.2.

```
 $ gprof2dot -f callgrind callgrind.out.34109 
warning: line 2: unexpected line
version: 1
digraph {
	graph [fontname=Arial, nodesep=0.125, ranksep=0.25];
	node [fontcolor=white, fontname=Arial, height=0, shape=box, style=filled, width=0];
	edge [fontname=Arial];
}
```

Begin of callgrind.out:
```
# callgrind format
version: 1
creator: callgrind-3.13.0
pid: 34109
cmd:  ./a.out
part: 1
```

**Comment by foxcpp** [comment]
Removal of first line in callgrind.out (`# callgrind format`) seems to make gprof2dot work correctly.

**Comment by foxcpp** [comment]
>#### 3.2.2. Description of Header Lines
>Basic information in the first lines of a profile data file:
>    * callgrind format [Callgrind]
>    This line specifies that the file is a callgrind profile, and it has to be the first line. It was added late to the format (with Valgrind 3.13) and is optional, as all readers also should work with older callgrind profiles not including this line. However, generation of this line is recommended to allow desktop environments and file managers to uniquely detect the format.

 \- Quoting http://valgrind.org/docs/manual/cl-format.html

**Comment by jrfonseca** [comment]
Thanks.  `# callgrind format` and any other line starting with `#` should now be properly ignored.

**Comment by gustafn** [comment]
Many thanks for fixing this! all the best
