### ISSUE TITLE
unexpected end of file

### ISSUE THREAD

**Issue by dickreuter** [jrfonseca/gprof2dot#41]
I'm trying to do gprof2dot.exe c:\temp\profile.pstat

the error is
unexpected end of file

Any suggestions are appreciated

**Comment by pianoslum** [comment]
I'm not a developer of the project, but I think attaching the file would help. Otherwise it's just guesswork...

**Comment by jrfonseca** [comment]
I suspect the problem is right on the command line.  Note that profiling format is *not* auto-detect.  You must pass `-f pstats` as described on https://github.com/jrfonseca/gprof2dot/blob/master/README.markdown#python-profile .  That is,

    gprof2dot.py -f pstats c:\temp\profile.pstat
