### ISSUE TITLE
Question: How to filter some no use functions

### ISSUE THREAD

**Issue by gggin** [jrfonseca/gprof2dot#46]
When I use 
```
python gprof2dot.py -n0.0001 -e0.0001 ./callgrind.out.28362 -f callgrind > out.dot && dot -Tpng out.dot -o out.pn
```
I see a lot of function in C runtime and Os system calls, I don't want to see them. Can I filter these things?

**Comment by jrfonseca** [comment]
There's no way to filter specific functions.  You can use the `--root`/`--leaf` options to get a subset of the graph, and you can use the `--path` to filter a specific module.  See `--help` for more info.
