### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character on systems without unicode support

### ISSUE THREAD

**Issue by szmoore** [jrfonseca/gprof2dot#47]
There appears to be a problem dealing with functions that have non-ascii encodable names:

```
File "redacted.py", line XX, in main
produce_profiles(redacted)
dot_writer.graph(parsed_profile, gprof2dot.themes['color'])
File "/vagrant/venv/lib/python3.5/site-packages/gprof2dot-2017.9.19-py3.5.egg/gprof2dot.py", line 3037, in graph
File "/vagrant/venv/lib/python3.5/site-packages/gprof2dot-2017.9.19-py3.5.egg/gprof2dot.py", line 3085, in node
File "/vagrant/venv/lib/python3.5/site-packages/gprof2dot-2017.9.19-py3.5.egg/gprof2dot.py", line 3110, in attr_list
File "/vagrant/venv/lib/python3.5/site-packages/gprof2dot-2017.9.19-py3.5.egg/gprof2dot.py", line 3123, in id
File "/vagrant/venv/lib/python3.5/site-packages/gprof2dot-2017.9.19-py3.5.egg/gprof2dot.py", line 3147, in write
UnicodeEncodeError: 'ascii' codec can't encode character '\xd7' in position 51: ordinal not in range(128)
```

**Comment by szmoore** [comment]
This seems to be an issue with Python2 vs Python3 Unicode vs String, 
There is an attempt to escape characters here:

https://github.com/jrfonseca/gprof2dot/blob/0891a148a7fc4110731ddd0b7573a4b352889a9d/gprof2dot.py#L3120

**Comment by szmoore** [comment]
Printing the offending string:
```
"redacted:67:initialize\\n12.29%\\n(7.89%)\\n29600\xd7
```

This could be a symptom of another issue where junk bytes are added to the `id` string?

**Comment by szmoore** [comment]
This is the `label` string, which is created here:
https://github.com/jrfonseca/gprof2dot/blob/0891a148a7fc4110731ddd0b7573a4b352889a9d/gprof2dot.py#L3033

**Comment by szmoore** [comment]
I have traced one of these errors to the `MULTIPLICATION_SIGN`
https://github.com/jrfonseca/gprof2dot/blob/0891a148a7fc4110731ddd0b7573a4b352889a9d/gprof2dot.py#L3024
```
(Pdb) MULTIPLICATION_SIGN.encode("utf8")
b'\xc3\x97'
```

**Comment by szmoore** [comment]
This might be caused by my environment lacking UTF8 fonts and falling back to ASCII which then fails

**Comment by jrfonseca** [comment]
The bug here is that you seem to be using gprof2dot as library directly (and you're failing to replicate what's uin https://github.com/jrfonseca/gprof2dot/blob/master/gprof2dot.py#L3291-L3300 )

Using gprof2dot as a library is not supported.   If you want to visualize profile data in a custom format, then the recommendation is either to use the JSON format input, or contribute the conversion code to gprof2dot .py

**Comment by szmoore** [comment]
Ok, apologies for wasting time.
