### ISSUE TITLE
Colour nodes by self-time

### ISSUE THREAD

**Issue by benjimin** [jrfonseca/gprof2dot#5]
Sometimes it is useful to draw attention to functions which have high self-time rather than total-time. (For example, to guide optimisation effort it can be desirable to focus on time-intensive core functions, with minimal distraction by the calling layers of light-weight wrapper functions.) I think it would be good if gprof2dot had *a command line argument to colour nodes by self-time instead of total-time.* It may also be worth switching to a smaller default skew value (since self-time < total-time).

Currently gprof2dot computes weights separately for functions and calls, but the same function weights are used for both pruning the graph (in Profile.prune) and for colouring the nodes (in the Dotwriter class). I think it would be undesirable to prune by self-time (because important context like "main" functions may be cut otherwise). The function weights are computed in Profile.prune, which has access to both total-time (TOTAL_TIME_RATIO) and self-time (TIME_RATIO). At present, one easy way to change the node colouring (and preserve the current pruning) is *at the very end of Profile.prune* (currently at line **648**) to "compute the prune ratios" a second time (but differently):
```
    colour_nodes_by_selftime = True
    if colour_nodes_by_selftime:
        for function in compat_itervalues(self.functions):
            try:
                function.weight = function[TIME_RATIO]
            except UndefinedEvent:
                pass
```

**Comment by aphirst** [comment]
I've tried running with --colour-nodes-by-selftime but I get the following error:

```
[adam@rakka ESTRUS]$ gprof ./estrus gmon.out | gprof2dot --total=callstacks --colour-nodes-by-selftime | dot -Tsvg -o output_TENSOR_matmul_stack.svg
Usage: 
	gprof2dot [options] [file] ...

gprof2dot: error: no such option: --colour-nodes-by-selftime
```
Is there something I'm doing wrong?

**Comment by jrfonseca** [comment]
@aphirst it looks alright; you probably have an old gprof2dot version

**Comment by aphirst** [comment]
@jrfonseca Ah, you're quite right! The version in the AUR is from 2015. The maintainer has already been notified but I modified the PKGBUILD and installed a local copy of the most recent version and the feature now seems to work! Thanks a lot! https://aur.archlinux.org/packages/gprof2dot/

My only remaining comment is that it's interesting that you chose to commit the British spelling of colour - I mean, I'm British too, but one usually expects the US spelling in software. Not that I'm bothered by this, of course!

**Comment by jrfonseca** [comment]
I missed the spelling difference in the @ppolewicz's commit a6504c882c2047fa2cfd99d2f655a985a9485b97.  I'm not British but I live in UK for some time so I think I unconsciously ignore the difference.  Indeed for consistency (not only with other software, but other gprof2dot options) we should be using `color`.  Now this has been released as is I don't won't to revert the spelling, but it should be easy to transparently support both spellings.
