### ISSUE TITLE
How to use --path option

### ISSUE THREAD

**Issue by fabiosangregorio** [jrfonseca/gprof2dot#67]
Hello. I am trying to exclude some nodes from my graph so that it can be less cluttered. Unfortunately, though, I was unable to find documentation on how to use the --path option. 

This is my graph:

![https://i.imgur.com/qhxLusT.png](https://i.imgur.com/qhxLusT.png)

What I'd like to do is remove:
* remote:758:fetch and its descendants
* cmd:542:<lambda> and its descendant

These are all methods of an external library ([GitPython](https://gitpython.readthedocs.io/en/stable/)), so that is why I'd like to remove them. 
Is this possible using the --path option (or with some others)? Could you please provide an example of how to achieve this?

Thank you in advance.

**Comment by fabiosangregorio** [comment]
Nevermind, got it. You need to input the absolute path, not relative to cwd.

An example:
```bash
python -m gprof2dot -f pstats -p /home/fabio/projects/credential-digger/ prof.out | dot -T png > output.png
```

Still, it would be nice to have some more documentation on this.
Also, the [usage documentation[(https://github.com/jrfonseca/gprof2dot#usage) is not up to date with the output of --help. 

You can close this when you read it. Thank you again! :)

**Comment by jrfonseca** [comment]
I'm glad you sorted out.   Cheers
