### ISSUE TITLE
how can i use gprof2dot on a binary executable file with a config file?

### ISSUE THREAD

**Issue by nickhuangxinyu** [jrfonseca/gprof2dot#68]
for normal excutable file to see running time picture.

I can do like this:

`gprof -p -q ./backtest | ~/gprof2dot/gprof2dot.py -n0 -e0 | dot -Tpng -o out.png`
`backtest` is my executable file.

but how if backtest need a config? for example, running command for backtest is:

`./backtest a.cfg > a`
i think:

`gprof -p -q ./backtest a.cfg > b | ~/gprof2dot/gprof2dot.py -n0 -e0 | dot -Tpng -o out.png`
this command is not good, how can i make it work

**Comment by jrfonseca** [comment]
Please follow the instructions in https://github.com/jrfonseca/gprof2dot/#gprof and run `man gprof` if still in doubt.

First you run your executable with any additional arguments your executable might.  Then you run gprof *without* any arguments, just path to the executable.

That is:

```
./backtest a.cfg > a
gprof ./backtest | ~/gprof2dot/gprof2dot.py -n0 -e0 | dot -Tpng -o out.png
```
