### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [jrfonseca/gprof2dot#70]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/118109190-74176280-b413-11eb-9617-be9c9c222dd6.png)

thank you  
best regards to you  
William

**Comment by jrfonseca** [comment]
`setup.py` is used for packaging.

If you just want to  gprof2dot from source tree, one doesn't need to use `setup.py`.  Just do

    ./gprof2dot.py
