### ISSUE TITLE
Analysis of test cases 

### ISSUE THREAD

**Issue by odidev** [jrfonseca/gprof2dot#74]
Hi Team, 

I tried testing gprof2dot package on Arm64 architectures and it is working successfully same as amd64 architecture result and there are no test cases passing. Here are the GHA logs: 

**GHA log:** https://github.com/bhumikapaharia/gprof2dot/runs/3586927137?check_suite_focus=true  

Could  you please let me know if I am missing something here for running the test cases? It will be really helpful to run the test cases for analysis of the package.

**Comment by jrfonseca** [comment]
gprof2dot is a pure python program.  It should work on any system that supports Python, regardless of the ISA.  Your GHA results seem to reflect that, as the tests seem to have completed successfully.
