### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by zbeekman** [jrfonseca/gprof2dot#8]
I am planning on submitting a [Homebrew](http://brew.sh) formula for easy installation on Mac, so long as @jrfonseca approves of the idea. I just wanted to check here first to make sure that you approved of the idea.

**Comment by jrfonseca** [comment]
@zbeekman, no objection.

**Comment by zbeekman** [comment]
After a bit of a headache due to some strange ruby handling of non-ascii characters, and slow waits for the testbot, gprof2dot is now available through [Homebrew](http://brew.sh). `brew update` to fetch new formulae, and `brew install gprof2dot` to install your lovely software!
