### ISSUE TITLE
Static analyze problem

### ISSUE THREAD

**Issue by sailorfeng** [jrfonseca/gprof2dot#84]
I try to run code static analyze on this project and got something in `gprof2dot.py`

```python
    profile = profile  # this line seems to be useless
    profile.prune(options.node_thres/100.0, options.edge_thres/100.0, options.filter_paths, options.color_nodes_by_selftime)
```

Is this line of code a typo?

**Comment by jrfonseca** [comment]
I think it was a left over from a code refactoring.  Fixed now.  Thanks
