### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [jrfonseca/gprof2dot#85]
Is it possible next time on release new version make the github release to have entry on https://github.com/jrfonseca/gprof2dot/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/

**Comment by jrfonseca** [comment]
It shouldn't be too hard to modify https://github.com/jrfonseca/gprof2dot/blob/master/.github/workflows/build.yml so it creates a GH release automatically.  I'll look into it next time.

In the meanwhile, I made a manual release, https://github.com/jrfonseca/gprof2dot/releases/tag/2022.07.29

**Comment by kloczek** [comment]
Thank you very much 👍 😄 
PS. Just noticed that my automation processed successfully your repo new release notification.
