### ISSUE TITLE
Version string not PEP-440 compliant

### ISSUE THREAD

**Issue by zbeekman** [jrfonseca/gprof2dot#9]
See here: https://github.com/tdsmith/homebrew-pypi-poet/issues/16#issuecomment-137909380

**Comment by jrfonseca** [comment]
https://www.python.org/dev/peps/pep-0440/ states that "Date based release segments are also permitted. " and gives a bunch of examples such as "2012.04".

**Comment by zbeekman** [comment]
ah, fair enough... I was led astray... btw, I've added a formula for `xdot` to Homebrew and am working on straightening out an issue surrounding the `gprof2dot` formula test for Homebrew. Hopefully I can resolve that issue, and then the `gprof2dot` formula should be accepted.

**Comment by zbeekman** [comment]
Here is a link to the PR if you're interested in following along: https://github.com/Homebrew/homebrew/pull/43583
