### ISSUE TITLE
Python can't execute script gprof2dot.py

### ISSUE THREAD

**Issue by bertulli** [jrfonseca/gprof2dot#95]
Hi, thanks for your work. I noticed that trying to clone the repo and simply running the script doesn't seem to work:
```
$ cat prof.out | ../gprof2dot/gprof2dot.py
Traceback (most recent call last):
  File "/home/abertulli/two_lidars/../gprof2dot/gprof2dot.py", line 3815, in <module>
    main()
  File "/home/abertulli/two_lidars/../gprof2dot/gprof2dot.py", line 3766, in main
    profile = parser.parse()
              ^^^^^^
UnboundLocalError: cannot access local variable 'parser' where it is not associated with a value
```
The version installed with `pip` works, but I invoke it with `gprof2dot`, not `gprof2dot.py`, if that is what is shown in the [README](https://github.com/jrfonseca/gprof2dot?tab=readme-ov-file#gprof). Am I doing something wong? Thanks!

**Comment by jrfonseca** [comment]
Thank you.
